// Generated by Haxe 3.4.0 (git build development @ 75c0f05)
#ifndef INCLUDED_stb_format_vorbis_VorbisTools
#define INCLUDED_stb_format_vorbis_VorbisTools

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS3(stb,format,vorbis,VorbisTools)
HX_DECLARE_CLASS4(stb,format,vorbis,data,IntPoint)

namespace stb{
namespace format{
namespace vorbis{


class HXCPP_CLASS_ATTRIBUTES VorbisTools_obj : public hx::Object
{
	public:
		typedef hx::Object super;
		typedef VorbisTools_obj OBJ_;
		VorbisTools_obj();

	public:
		enum { _hx_ClassId = 0x2983de5d };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="stb.format.vorbis.VorbisTools")
			{ return hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return hx::Object::operator new(inSize+extra,false,"stb.format.vorbis.VorbisTools"); }

		hx::ObjectPtr< VorbisTools_obj > __new() {
			hx::ObjectPtr< VorbisTools_obj > __this = new VorbisTools_obj();
			__this->__construct();
			return __this;
		}

		static hx::ObjectPtr< VorbisTools_obj > __alloc(hx::Ctx *_hx_ctx) {
			VorbisTools_obj *__this = (VorbisTools_obj*)(hx::Ctx::alloc(_hx_ctx, sizeof(VorbisTools_obj), false, "stb.format.vorbis.VorbisTools"));
			*(void **)__this = VorbisTools_obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(hx::DynamicArray inArgs);
		//~VorbisTools_obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, hx::PropertyAccess inCallProp);
		static bool __SetStatic(const ::String &inString, Dynamic &ioValue, hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_HCSTRING("VorbisTools","\xa8","\xa9","\x86","\x30"); }

		static void __boot();
		static int EOP;
		static ::Array< ::Dynamic> integerDivideTable;
		static Float M__PI;
		static int DIVTAB_NUMER;
		static int DIVTAB_DENOM;
		static ::Array< Float > INVERSE_DB_TABLE;
		static void _hx_assert(bool b, ::Dynamic p);
		static ::Dynamic _hx_assert_dyn();

		static  ::Dynamic neighbors(::Array< int > x,int n);
		static ::Dynamic neighbors_dyn();

		static Float floatUnpack(int x);
		static ::Dynamic floatUnpack_dyn();

		static int bitReverse(int n);
		static ::Dynamic bitReverse_dyn();

		static int pointCompare( ::stb::format::vorbis::data::IntPoint a, ::stb::format::vorbis::data::IntPoint b);
		static ::Dynamic pointCompare_dyn();

		static int uintAsc(int a,int b);
		static ::Dynamic uintAsc_dyn();

		static int lookup1Values(int entries,int dim);
		static ::Dynamic lookup1Values_dyn();

		static void computeWindow(int n,::Array< Float > window);
		static ::Dynamic computeWindow_dyn();

		static Float square(Float f);
		static ::Dynamic square_dyn();

		static void computeBitReverse(int n,::Array< int > rev);
		static ::Dynamic computeBitReverse_dyn();

		static void computeTwiddleFactors(int n,::Array< Float > af,::Array< Float > bf,::Array< Float > cf);
		static ::Dynamic computeTwiddleFactors_dyn();

		static void drawLine(::Array< Float > output,int x0,int y0,int x1,int y1,int n);
		static ::Dynamic drawLine_dyn();

		static int predictPoint(int x,int x0,int x1,int y0,int y1);
		static ::Dynamic predictPoint_dyn();

		static ::Array< Float > emptyFloatVector(int len);
		static ::Dynamic emptyFloatVector_dyn();

		static ::Array< Float > copyVector(::Array< Float > source);
		static ::Dynamic copyVector_dyn();

};

} // end namespace stb
} // end namespace format
} // end namespace vorbis

#endif /* INCLUDED_stb_format_vorbis_VorbisTools */ 
