// Generated by Haxe 3.4.0 (git build development @ 75c0f05)
#include <hxcpp.h>

#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
#ifndef INCLUDED_haxe_ds_StringMap
#include <haxe/ds/StringMap.h>
#endif
#ifndef INCLUDED_stb_format_vorbis_data_Comment
#include <stb/format/vorbis/data/Comment.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_70258c38f5cdf4ee_101_new,"stb.format.vorbis.data.Comment","new",0x79878ede,"stb.format.vorbis.data.Comment.new","stb/format/vorbis/data/Comment.hx",101,0x38e414d2)
HX_DEFINE_STACK_FRAME(_hx_pos_70258c38f5cdf4ee_12_get_title,"stb.format.vorbis.data.Comment","get_title",0x9b0b22ed,"stb.format.vorbis.data.Comment.get_title","stb/format/vorbis/data/Comment.hx",12,0x38e414d2)
HX_DEFINE_STACK_FRAME(_hx_pos_70258c38f5cdf4ee_17_get_loopStart,"stb.format.vorbis.data.Comment","get_loopStart",0x0b216f33,"stb.format.vorbis.data.Comment.get_loopStart","stb/format/vorbis/data/Comment.hx",17,0x38e414d2)
HX_DEFINE_STACK_FRAME(_hx_pos_70258c38f5cdf4ee_22_get_loopLength,"stb.format.vorbis.data.Comment","get_loopLength",0x4b2d10f5,"stb.format.vorbis.data.Comment.get_loopLength","stb/format/vorbis/data/Comment.hx",22,0x38e414d2)
HX_DEFINE_STACK_FRAME(_hx_pos_70258c38f5cdf4ee_27_get_version,"stb.format.vorbis.data.Comment","get_version",0x65dfb3ad,"stb.format.vorbis.data.Comment.get_version","stb/format/vorbis/data/Comment.hx",27,0x38e414d2)
HX_DEFINE_STACK_FRAME(_hx_pos_70258c38f5cdf4ee_32_get_album,"stb.format.vorbis.data.Comment","get_album",0xac5c2084,"stb.format.vorbis.data.Comment.get_album","stb/format/vorbis/data/Comment.hx",32,0x38e414d2)
HX_DEFINE_STACK_FRAME(_hx_pos_70258c38f5cdf4ee_37_get_organization,"stb.format.vorbis.data.Comment","get_organization",0xbd969cbe,"stb.format.vorbis.data.Comment.get_organization","stb/format/vorbis/data/Comment.hx",37,0x38e414d2)
HX_DEFINE_STACK_FRAME(_hx_pos_70258c38f5cdf4ee_42_get_tracknumber,"stb.format.vorbis.data.Comment","get_tracknumber",0x01584aa9,"stb.format.vorbis.data.Comment.get_tracknumber","stb/format/vorbis/data/Comment.hx",42,0x38e414d2)
HX_DEFINE_STACK_FRAME(_hx_pos_70258c38f5cdf4ee_47_get_performer,"stb.format.vorbis.data.Comment","get_performer",0xb60c4723,"stb.format.vorbis.data.Comment.get_performer","stb/format/vorbis/data/Comment.hx",47,0x38e414d2)
HX_DEFINE_STACK_FRAME(_hx_pos_70258c38f5cdf4ee_52_get_copyright,"stb.format.vorbis.data.Comment","get_copyright",0x359b9bdc,"stb.format.vorbis.data.Comment.get_copyright","stb/format/vorbis/data/Comment.hx",52,0x38e414d2)
HX_DEFINE_STACK_FRAME(_hx_pos_70258c38f5cdf4ee_57_get_license,"stb.format.vorbis.data.Comment","get_license",0xb336a016,"stb.format.vorbis.data.Comment.get_license","stb/format/vorbis/data/Comment.hx",57,0x38e414d2)
HX_DEFINE_STACK_FRAME(_hx_pos_70258c38f5cdf4ee_62_get_artist,"stb.format.vorbis.data.Comment","get_artist",0xa4848fd2,"stb.format.vorbis.data.Comment.get_artist","stb/format/vorbis/data/Comment.hx",62,0x38e414d2)
HX_DEFINE_STACK_FRAME(_hx_pos_70258c38f5cdf4ee_67_get_description,"stb.format.vorbis.data.Comment","get_description",0x4b954411,"stb.format.vorbis.data.Comment.get_description","stb/format/vorbis/data/Comment.hx",67,0x38e414d2)
HX_DEFINE_STACK_FRAME(_hx_pos_70258c38f5cdf4ee_72_get_genre,"stb.format.vorbis.data.Comment","get_genre",0x1c2c3598,"stb.format.vorbis.data.Comment.get_genre","stb/format/vorbis/data/Comment.hx",72,0x38e414d2)
HX_DEFINE_STACK_FRAME(_hx_pos_70258c38f5cdf4ee_77_get_date,"stb.format.vorbis.data.Comment","get_date",0x3f910a79,"stb.format.vorbis.data.Comment.get_date","stb/format/vorbis/data/Comment.hx",77,0x38e414d2)
HX_DEFINE_STACK_FRAME(_hx_pos_70258c38f5cdf4ee_82_get_location,"stb.format.vorbis.data.Comment","get_location",0xcc6ba400,"stb.format.vorbis.data.Comment.get_location","stb/format/vorbis/data/Comment.hx",82,0x38e414d2)
HX_DEFINE_STACK_FRAME(_hx_pos_70258c38f5cdf4ee_87_get_contact,"stb.format.vorbis.data.Comment","get_contact",0x02624735,"stb.format.vorbis.data.Comment.get_contact","stb/format/vorbis/data/Comment.hx",87,0x38e414d2)
HX_DEFINE_STACK_FRAME(_hx_pos_70258c38f5cdf4ee_92_get_isrc,"stb.format.vorbis.data.Comment","get_isrc",0x42ecc266,"stb.format.vorbis.data.Comment.get_isrc","stb/format/vorbis/data/Comment.hx",92,0x38e414d2)
HX_DEFINE_STACK_FRAME(_hx_pos_70258c38f5cdf4ee_97_get_artists,"stb.format.vorbis.data.Comment","get_artists",0x4f794861,"stb.format.vorbis.data.Comment.get_artists","stb/format/vorbis/data/Comment.hx",97,0x38e414d2)
HX_DEFINE_STACK_FRAME(_hx_pos_70258c38f5cdf4ee_104_add,"stb.format.vorbis.data.Comment","add",0x797db09f,"stb.format.vorbis.data.Comment.add","stb/format/vorbis/data/Comment.hx",104,0x38e414d2)
HX_DEFINE_STACK_FRAME(_hx_pos_70258c38f5cdf4ee_113_getString,"stb.format.vorbis.data.Comment","getString",0xd4ad6305,"stb.format.vorbis.data.Comment.getString","stb/format/vorbis/data/Comment.hx",113,0x38e414d2)
HX_DEFINE_STACK_FRAME(_hx_pos_70258c38f5cdf4ee_122_getArray,"stb.format.vorbis.data.Comment","getArray",0x02d975e5,"stb.format.vorbis.data.Comment.getArray","stb/format/vorbis/data/Comment.hx",122,0x38e414d2)
namespace stb{
namespace format{
namespace vorbis{
namespace data{

void Comment_obj::__construct(){
            	HX_GC_STACKFRAME(&_hx_pos_70258c38f5cdf4ee_101_new)
            	HX_STACK_THIS(this)
HXLINE( 101)		this->data =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
            	}

Dynamic Comment_obj::__CreateEmpty() { return new Comment_obj; }

void *Comment_obj::_hx_vtable = 0;

Dynamic Comment_obj::__Create(hx::DynamicArray inArgs)
{
	hx::ObjectPtr< Comment_obj > _hx_result = new Comment_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool Comment_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x244a3c36;
}

::String Comment_obj::get_title(){
            	HX_STACKFRAME(&_hx_pos_70258c38f5cdf4ee_12_get_title)
            	HX_STACK_THIS(this)
HXLINE(  12)		return this->getString(HX_("title",98,15,3b,10));
            	}


HX_DEFINE_DYNAMIC_FUNC0(Comment_obj,get_title,return )

 ::Dynamic Comment_obj::get_loopStart(){
            	HX_STACKFRAME(&_hx_pos_70258c38f5cdf4ee_17_get_loopStart)
            	HX_STACK_THIS(this)
HXLINE(  17)		return ::Std_obj::parseInt(this->getString(HX_("loopstart",7e,23,8a,1e)));
            	}


HX_DEFINE_DYNAMIC_FUNC0(Comment_obj,get_loopStart,return )

 ::Dynamic Comment_obj::get_loopLength(){
            	HX_STACKFRAME(&_hx_pos_70258c38f5cdf4ee_22_get_loopLength)
            	HX_STACK_THIS(this)
HXLINE(  22)		return ::Std_obj::parseInt(this->getString(HX_("looplength",4a,1e,62,33)));
            	}


HX_DEFINE_DYNAMIC_FUNC0(Comment_obj,get_loopLength,return )

::String Comment_obj::get_version(){
            	HX_STACKFRAME(&_hx_pos_70258c38f5cdf4ee_27_get_version)
            	HX_STACK_THIS(this)
HXLINE(  27)		return this->getString(HX_("version",18,e7,f1,7c));
            	}


HX_DEFINE_DYNAMIC_FUNC0(Comment_obj,get_version,return )

::String Comment_obj::get_album(){
            	HX_STACKFRAME(&_hx_pos_70258c38f5cdf4ee_32_get_album)
            	HX_STACK_THIS(this)
HXLINE(  32)		return this->getString(HX_("album",2f,13,8c,21));
            	}


HX_DEFINE_DYNAMIC_FUNC0(Comment_obj,get_album,return )

::String Comment_obj::get_organization(){
            	HX_STACKFRAME(&_hx_pos_70258c38f5cdf4ee_37_get_organization)
            	HX_STACK_THIS(this)
HXLINE(  37)		return this->getString(HX_("organization",73,25,db,c0));
            	}


HX_DEFINE_DYNAMIC_FUNC0(Comment_obj,get_organization,return )

::String Comment_obj::get_tracknumber(){
            	HX_STACKFRAME(&_hx_pos_70258c38f5cdf4ee_42_get_tracknumber)
            	HX_STACK_THIS(this)
HXLINE(  42)		return this->getString(HX_("tracknumber",94,0f,e0,14));
            	}


HX_DEFINE_DYNAMIC_FUNC0(Comment_obj,get_tracknumber,return )

::String Comment_obj::get_performer(){
            	HX_STACKFRAME(&_hx_pos_70258c38f5cdf4ee_47_get_performer)
            	HX_STACK_THIS(this)
HXLINE(  47)		return this->getString(HX_("performer",4e,6b,a2,5c));
            	}


HX_DEFINE_DYNAMIC_FUNC0(Comment_obj,get_performer,return )

::String Comment_obj::get_copyright(){
            	HX_STACKFRAME(&_hx_pos_70258c38f5cdf4ee_52_get_copyright)
            	HX_STACK_THIS(this)
HXLINE(  52)		return this->getString(HX_("copyright",07,c0,31,dc));
            	}


HX_DEFINE_DYNAMIC_FUNC0(Comment_obj,get_copyright,return )

::String Comment_obj::get_license(){
            	HX_STACKFRAME(&_hx_pos_70258c38f5cdf4ee_57_get_license)
            	HX_STACK_THIS(this)
HXLINE(  57)		return this->getString(HX_("license",81,d3,48,ca));
            	}


HX_DEFINE_DYNAMIC_FUNC0(Comment_obj,get_license,return )

::String Comment_obj::get_artist(){
            	HX_STACKFRAME(&_hx_pos_70258c38f5cdf4ee_62_get_artist)
            	HX_STACK_THIS(this)
HXLINE(  62)		return this->getString(HX_("artist",c7,f2,48,b9));
            	}


HX_DEFINE_DYNAMIC_FUNC0(Comment_obj,get_artist,return )

::String Comment_obj::get_description(){
            	HX_STACKFRAME(&_hx_pos_70258c38f5cdf4ee_67_get_description)
            	HX_STACK_THIS(this)
HXLINE(  67)		return this->getString(HX_("description",fc,08,1d,5f));
            	}


HX_DEFINE_DYNAMIC_FUNC0(Comment_obj,get_description,return )

::String Comment_obj::get_genre(){
            	HX_STACKFRAME(&_hx_pos_70258c38f5cdf4ee_72_get_genre)
            	HX_STACK_THIS(this)
HXLINE(  72)		return this->getString(HX_("genre",43,28,5c,91));
            	}


HX_DEFINE_DYNAMIC_FUNC0(Comment_obj,get_genre,return )

::String Comment_obj::get_date(){
            	HX_STACKFRAME(&_hx_pos_70258c38f5cdf4ee_77_get_date)
            	HX_STACK_THIS(this)
HXLINE(  77)		return this->getString(HX_("date",2e,56,63,42));
            	}


HX_DEFINE_DYNAMIC_FUNC0(Comment_obj,get_date,return )

::String Comment_obj::get_location(){
            	HX_STACKFRAME(&_hx_pos_70258c38f5cdf4ee_82_get_location)
            	HX_STACK_THIS(this)
HXLINE(  82)		return this->getString(HX_("location",35,6e,46,e5));
            	}


HX_DEFINE_DYNAMIC_FUNC0(Comment_obj,get_location,return )

::String Comment_obj::get_contact(){
            	HX_STACKFRAME(&_hx_pos_70258c38f5cdf4ee_87_get_contact)
            	HX_STACK_THIS(this)
HXLINE(  87)		return this->getString(HX_("contact",a0,7a,74,19));
            	}


HX_DEFINE_DYNAMIC_FUNC0(Comment_obj,get_contact,return )

::String Comment_obj::get_isrc(){
            	HX_STACKFRAME(&_hx_pos_70258c38f5cdf4ee_92_get_isrc)
            	HX_STACK_THIS(this)
HXLINE(  92)		return this->getString(HX_("isrc",1b,0e,bf,45));
            	}


HX_DEFINE_DYNAMIC_FUNC0(Comment_obj,get_isrc,return )

::Array< ::String > Comment_obj::get_artists(){
            	HX_STACKFRAME(&_hx_pos_70258c38f5cdf4ee_97_get_artists)
            	HX_STACK_THIS(this)
HXLINE(  97)		return this->getArray(HX_("artist",c7,f2,48,b9));
            	}


HX_DEFINE_DYNAMIC_FUNC0(Comment_obj,get_artists,return )

void Comment_obj::add(::String key,::String value){
            	HX_STACKFRAME(&_hx_pos_70258c38f5cdf4ee_104_add)
            	HX_STACK_THIS(this)
            	HX_STACK_ARG(key,"key")
            	HX_STACK_ARG(value,"value")
HXLINE( 105)		key = key.toLowerCase();
HXLINE( 106)		if (this->data->exists(key)) {
HXLINE( 107)			( (::Array< ::String >)(this->data->get(key)) )->push(value);
            		}
            		else {
HXLINE( 109)			this->data->set(key,::Array_obj< ::String >::__new(1)->init(0,value));
            		}
            	}


HX_DEFINE_DYNAMIC_FUNC2(Comment_obj,add,(void))

::String Comment_obj::getString(::String key){
            	HX_STACKFRAME(&_hx_pos_70258c38f5cdf4ee_113_getString)
            	HX_STACK_THIS(this)
            	HX_STACK_ARG(key,"key")
HXLINE( 114)		key = key.toLowerCase();
HXLINE( 115)		if (this->data->exists(key)) {
HXLINE( 115)			return this->data->get(key)->__GetItem((int)0);
            		}
            		else {
HXLINE( 115)			return null();
            		}
HXDLIN( 115)		return null();
            	}


HX_DEFINE_DYNAMIC_FUNC1(Comment_obj,getString,return )

::Array< ::String > Comment_obj::getArray(::String key){
            	HX_STACKFRAME(&_hx_pos_70258c38f5cdf4ee_122_getArray)
            	HX_STACK_THIS(this)
            	HX_STACK_ARG(key,"key")
HXLINE( 123)		key = key.toLowerCase();
HXLINE( 124)		if (this->data->exists(key)) {
HXLINE( 124)			return this->data->get(key);
            		}
            		else {
HXLINE( 124)			return null();
            		}
HXDLIN( 124)		return null();
            	}


HX_DEFINE_DYNAMIC_FUNC1(Comment_obj,getArray,return )


hx::ObjectPtr< Comment_obj > Comment_obj::__new() {
	hx::ObjectPtr< Comment_obj > __this = new Comment_obj();
	__this->__construct();
	return __this;
}

hx::ObjectPtr< Comment_obj > Comment_obj::__alloc(hx::Ctx *_hx_ctx) {
	Comment_obj *__this = (Comment_obj*)(hx::Ctx::alloc(_hx_ctx, sizeof(Comment_obj), true, "stb.format.vorbis.data.Comment"));
	*(void **)__this = Comment_obj::_hx_vtable;
	__this->__construct();
	return __this;
}

Comment_obj::Comment_obj()
{
}

void Comment_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(Comment);
	HX_MARK_MEMBER_NAME(data,"data");
	HX_MARK_END_CLASS();
}

void Comment_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(data,"data");
}

hx::Val Comment_obj::__Field(const ::String &inName,hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"add") ) { return hx::Val( add_dyn()); }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"data") ) { return hx::Val( data); }
		if (HX_FIELD_EQ(inName,"date") ) { if (inCallProp == hx::paccAlways) return hx::Val(get_date()); }
		if (HX_FIELD_EQ(inName,"isrc") ) { if (inCallProp == hx::paccAlways) return hx::Val(get_isrc()); }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"title") ) { if (inCallProp == hx::paccAlways) return hx::Val(get_title()); }
		if (HX_FIELD_EQ(inName,"album") ) { if (inCallProp == hx::paccAlways) return hx::Val(get_album()); }
		if (HX_FIELD_EQ(inName,"genre") ) { if (inCallProp == hx::paccAlways) return hx::Val(get_genre()); }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"artist") ) { if (inCallProp == hx::paccAlways) return hx::Val(get_artist()); }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"version") ) { if (inCallProp == hx::paccAlways) return hx::Val(get_version()); }
		if (HX_FIELD_EQ(inName,"license") ) { if (inCallProp == hx::paccAlways) return hx::Val(get_license()); }
		if (HX_FIELD_EQ(inName,"contact") ) { if (inCallProp == hx::paccAlways) return hx::Val(get_contact()); }
		if (HX_FIELD_EQ(inName,"artists") ) { if (inCallProp == hx::paccAlways) return hx::Val(get_artists()); }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"get_date") ) { return hx::Val( get_date_dyn()); }
		if (HX_FIELD_EQ(inName,"location") ) { if (inCallProp == hx::paccAlways) return hx::Val(get_location()); }
		if (HX_FIELD_EQ(inName,"get_isrc") ) { return hx::Val( get_isrc_dyn()); }
		if (HX_FIELD_EQ(inName,"getArray") ) { return hx::Val( getArray_dyn()); }
		break;
	case 9:
		if (HX_FIELD_EQ(inName,"get_title") ) { return hx::Val( get_title_dyn()); }
		if (HX_FIELD_EQ(inName,"loopStart") ) { if (inCallProp == hx::paccAlways) return hx::Val(get_loopStart()); }
		if (HX_FIELD_EQ(inName,"get_album") ) { return hx::Val( get_album_dyn()); }
		if (HX_FIELD_EQ(inName,"performer") ) { if (inCallProp == hx::paccAlways) return hx::Val(get_performer()); }
		if (HX_FIELD_EQ(inName,"copyright") ) { if (inCallProp == hx::paccAlways) return hx::Val(get_copyright()); }
		if (HX_FIELD_EQ(inName,"get_genre") ) { return hx::Val( get_genre_dyn()); }
		if (HX_FIELD_EQ(inName,"getString") ) { return hx::Val( getString_dyn()); }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"loopLength") ) { if (inCallProp == hx::paccAlways) return hx::Val(get_loopLength()); }
		if (HX_FIELD_EQ(inName,"get_artist") ) { return hx::Val( get_artist_dyn()); }
		break;
	case 11:
		if (HX_FIELD_EQ(inName,"get_version") ) { return hx::Val( get_version_dyn()); }
		if (HX_FIELD_EQ(inName,"tracknumber") ) { if (inCallProp == hx::paccAlways) return hx::Val(get_tracknumber()); }
		if (HX_FIELD_EQ(inName,"get_license") ) { return hx::Val( get_license_dyn()); }
		if (HX_FIELD_EQ(inName,"description") ) { if (inCallProp == hx::paccAlways) return hx::Val(get_description()); }
		if (HX_FIELD_EQ(inName,"get_contact") ) { return hx::Val( get_contact_dyn()); }
		if (HX_FIELD_EQ(inName,"get_artists") ) { return hx::Val( get_artists_dyn()); }
		break;
	case 12:
		if (HX_FIELD_EQ(inName,"organization") ) { if (inCallProp == hx::paccAlways) return hx::Val(get_organization()); }
		if (HX_FIELD_EQ(inName,"get_location") ) { return hx::Val( get_location_dyn()); }
		break;
	case 13:
		if (HX_FIELD_EQ(inName,"get_loopStart") ) { return hx::Val( get_loopStart_dyn()); }
		if (HX_FIELD_EQ(inName,"get_performer") ) { return hx::Val( get_performer_dyn()); }
		if (HX_FIELD_EQ(inName,"get_copyright") ) { return hx::Val( get_copyright_dyn()); }
		break;
	case 14:
		if (HX_FIELD_EQ(inName,"get_loopLength") ) { return hx::Val( get_loopLength_dyn()); }
		break;
	case 15:
		if (HX_FIELD_EQ(inName,"get_tracknumber") ) { return hx::Val( get_tracknumber_dyn()); }
		if (HX_FIELD_EQ(inName,"get_description") ) { return hx::Val( get_description_dyn()); }
		break;
	case 16:
		if (HX_FIELD_EQ(inName,"get_organization") ) { return hx::Val( get_organization_dyn()); }
	}
	return super::__Field(inName,inCallProp);
}

hx::Val Comment_obj::__SetField(const ::String &inName,const hx::Val &inValue,hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"data") ) { data=inValue.Cast<  ::haxe::ds::StringMap >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void Comment_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_HCSTRING("data","\x2a","\x56","\x63","\x42"));
	outFields->push(HX_HCSTRING("title","\x98","\x15","\x3b","\x10"));
	outFields->push(HX_HCSTRING("loopStart","\x5e","\x93","\xb7","\xb1"));
	outFields->push(HX_HCSTRING("loopLength","\x6a","\x92","\xf6","\x67"));
	outFields->push(HX_HCSTRING("version","\x18","\xe7","\xf1","\x7c"));
	outFields->push(HX_HCSTRING("album","\x2f","\x13","\x8c","\x21"));
	outFields->push(HX_HCSTRING("organization","\x73","\x25","\xdb","\xc0"));
	outFields->push(HX_HCSTRING("tracknumber","\x94","\x0f","\xe0","\x14"));
	outFields->push(HX_HCSTRING("performer","\x4e","\x6b","\xa2","\x5c"));
	outFields->push(HX_HCSTRING("copyright","\x07","\xc0","\x31","\xdc"));
	outFields->push(HX_HCSTRING("license","\x81","\xd3","\x48","\xca"));
	outFields->push(HX_HCSTRING("artist","\xc7","\xf2","\x48","\xb9"));
	outFields->push(HX_HCSTRING("description","\xfc","\x08","\x1d","\x5f"));
	outFields->push(HX_HCSTRING("genre","\x43","\x28","\x5c","\x91"));
	outFields->push(HX_HCSTRING("date","\x2e","\x56","\x63","\x42"));
	outFields->push(HX_HCSTRING("location","\x35","\x6e","\x46","\xe5"));
	outFields->push(HX_HCSTRING("contact","\xa0","\x7a","\x74","\x19"));
	outFields->push(HX_HCSTRING("isrc","\x1b","\x0e","\xbf","\x45"));
	outFields->push(HX_HCSTRING("artists","\xcc","\x7b","\x8b","\x66"));
	super::__GetFields(outFields);
};

#if HXCPP_SCRIPTABLE
static hx::StorageInfo Comment_obj_sMemberStorageInfo[] = {
	{hx::fsObject /*::haxe::ds::StringMap*/ ,(int)offsetof(Comment_obj,data),HX_HCSTRING("data","\x2a","\x56","\x63","\x42")},
	{ hx::fsUnknown, 0, null()}
};
static hx::StaticInfo *Comment_obj_sStaticStorageInfo = 0;
#endif

static ::String Comment_obj_sMemberFields[] = {
	HX_HCSTRING("data","\x2a","\x56","\x63","\x42"),
	HX_HCSTRING("get_title","\xef","\x71","\xe4","\x53"),
	HX_HCSTRING("get_loopStart","\x35","\x67","\x1b","\x73"),
	HX_HCSTRING("get_loopLength","\xb3","\x1a","\xec","\xdd"),
	HX_HCSTRING("get_version","\x2f","\x47","\xec","\x02"),
	HX_HCSTRING("get_album","\x86","\x6f","\x35","\x65"),
	HX_HCSTRING("get_organization","\xfc","\x11","\x7a","\xc5"),
	HX_HCSTRING("get_tracknumber","\x2b","\xc7","\xc1","\xd5"),
	HX_HCSTRING("get_performer","\x25","\x3f","\x06","\x1e"),
	HX_HCSTRING("get_copyright","\xde","\x93","\x95","\x9d"),
	HX_HCSTRING("get_license","\x98","\x33","\x43","\x50"),
	HX_HCSTRING("get_artist","\x90","\x62","\xd0","\xa9"),
	HX_HCSTRING("get_description","\x93","\xc0","\xfe","\x1f"),
	HX_HCSTRING("get_genre","\x9a","\x84","\x05","\xd5"),
	HX_HCSTRING("get_date","\xb7","\x11","\x1e","\xc2"),
	HX_HCSTRING("get_location","\x3e","\x22","\x60","\x9a"),
	HX_HCSTRING("get_contact","\xb7","\xda","\x6e","\x9f"),
	HX_HCSTRING("get_isrc","\xa4","\xc9","\x79","\xc5"),
	HX_HCSTRING("get_artists","\xe3","\xdb","\x85","\xec"),
	HX_HCSTRING("add","\x21","\xf2","\x49","\x00"),
	HX_HCSTRING("getString","\x07","\xb2","\x86","\x8d"),
	HX_HCSTRING("getArray","\x23","\x7d","\x66","\x85"),
	::String(null()) };

static void Comment_obj_sMarkStatics(HX_MARK_PARAMS) {
	HX_MARK_MEMBER_NAME(Comment_obj::__mClass,"__mClass");
};

#ifdef HXCPP_VISIT_ALLOCS
static void Comment_obj_sVisitStatics(HX_VISIT_PARAMS) {
	HX_VISIT_MEMBER_NAME(Comment_obj::__mClass,"__mClass");
};

#endif

hx::Class Comment_obj::__mClass;

void Comment_obj::__register()
{
	hx::Object *dummy = new Comment_obj;
	Comment_obj::_hx_vtable = *(void **)dummy;
	hx::Static(__mClass) = new hx::Class_obj();
	__mClass->mName = HX_HCSTRING("stb.format.vorbis.data.Comment","\xec","\x87","\x6b","\x4e");
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &hx::Class_obj::SetNoStaticField;
	__mClass->mMarkFunc = Comment_obj_sMarkStatics;
	__mClass->mStatics = hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = hx::Class_obj::dupFunctions(Comment_obj_sMemberFields);
	__mClass->mCanCast = hx::TCanCast< Comment_obj >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = Comment_obj_sVisitStatics;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Comment_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Comment_obj_sStaticStorageInfo;
#endif
	hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace stb
} // end namespace format
} // end namespace vorbis
} // end namespace data
