// Generated by Haxe 3.4.0 (git build development @ 75c0f05)
#include <hxcpp.h>

namespace hx {
}

hx::Resource __Resources[] = {
	{ ::String(null()),0,0 }
};

namespace hx { Resource *GetResources() { return __Resources; } }
