// Generated by Haxe 3.4.0 (git build development @ 75c0f05)
#include <hxcpp.h>

#ifndef INCLUDED_stb_format_vorbis__VorbisDecodeState_FindPageResult
#include <stb/format/vorbis/_VorbisDecodeState/FindPageResult.h>
#endif
namespace stb{
namespace format{
namespace vorbis{
namespace _VorbisDecodeState{

::stb::format::vorbis::_VorbisDecodeState::FindPageResult FindPageResult_obj::Found(int end,bool last)
{
	return hx::CreateEnum< FindPageResult_obj >(HX_("Found",22,72,c4,97),0,2)->_hx_init(0,end)->_hx_init(1,last);
}

::stb::format::vorbis::_VorbisDecodeState::FindPageResult FindPageResult_obj::NotFound;

bool FindPageResult_obj::__GetStatic(const ::String &inName, ::Dynamic &outValue, hx::PropertyAccess inCallProp)
{
	if (inName==HX_("Found",22,72,c4,97)) { outValue = FindPageResult_obj::Found_dyn(); return true; }
	if (inName==HX_("NotFound",4f,90,57,6e)) { outValue = FindPageResult_obj::NotFound; return true; }
	return super::__GetStatic(inName, outValue, inCallProp);
}

HX_DEFINE_CREATE_ENUM(FindPageResult_obj)

int FindPageResult_obj::__FindIndex(::String inName)
{
	if (inName==HX_("Found",22,72,c4,97)) return 0;
	if (inName==HX_("NotFound",4f,90,57,6e)) return 1;
	return super::__FindIndex(inName);
}

STATIC_HX_DEFINE_DYNAMIC_FUNC2(FindPageResult_obj,Found,return)

int FindPageResult_obj::__FindArgCount(::String inName)
{
	if (inName==HX_("Found",22,72,c4,97)) return 2;
	if (inName==HX_("NotFound",4f,90,57,6e)) return 0;
	return super::__FindArgCount(inName);
}

hx::Val FindPageResult_obj::__Field(const ::String &inName,hx::PropertyAccess inCallProp)
{
	if (inName==HX_("Found",22,72,c4,97)) return Found_dyn();
	if (inName==HX_("NotFound",4f,90,57,6e)) return NotFound;
	return super::__Field(inName,inCallProp);
}

static ::String FindPageResult_obj_sStaticFields[] = {
	HX_("Found",22,72,c4,97),
	HX_("NotFound",4f,90,57,6e),
	::String(null())
};

static void FindPageResult_obj_sMarkStatics(HX_MARK_PARAMS) {
	HX_MARK_MEMBER_NAME(FindPageResult_obj::NotFound,"NotFound");
};

#ifdef HXCPP_VISIT_ALLOCS
static void FindPageResult_obj_sVisitStatic(HX_VISIT_PARAMS) {
	HX_VISIT_MEMBER_NAME(FindPageResult_obj::__mClass,"__mClass");
	HX_VISIT_MEMBER_NAME(FindPageResult_obj::NotFound,"NotFound");
};
#endif

hx::Class FindPageResult_obj::__mClass;

Dynamic __Create_FindPageResult_obj() { return new FindPageResult_obj; }

void FindPageResult_obj::__register()
{

hx::Static(__mClass) = hx::_hx_RegisterClass(HX_HCSTRING("stb.format.vorbis._VorbisDecodeState.FindPageResult","\x71","\x40","\xfe","\xa0"), hx::TCanCast< FindPageResult_obj >,FindPageResult_obj_sStaticFields,0,
	&__Create_FindPageResult_obj, &__Create,
	&super::__SGetClass(), &CreateFindPageResult_obj, FindPageResult_obj_sMarkStatics
#ifdef HXCPP_VISIT_ALLOCS
    , FindPageResult_obj_sVisitStatic
#endif
#ifdef HXCPP_SCRIPTABLE
    , 0
#endif
);
	__mClass->mGetStaticField = &FindPageResult_obj::__GetStatic;
}

void FindPageResult_obj::__boot()
{
NotFound = hx::CreateEnum< FindPageResult_obj >(HX_HCSTRING("NotFound","\x4f","\x90","\x57","\x6e"),1,0);
}


} // end namespace stb
} // end namespace format
} // end namespace vorbis
} // end namespace _VorbisDecodeState
