// Generated by Haxe 3.4.0 (git build development @ 75c0f05)
#ifndef INCLUDED_Ogg2WavSys
#define INCLUDED_Ogg2WavSys

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS0(Ogg2WavSys)



class HXCPP_CLASS_ATTRIBUTES Ogg2WavSys_obj : public hx::Object
{
	public:
		typedef hx::Object super;
		typedef Ogg2WavSys_obj OBJ_;
		Ogg2WavSys_obj();

	public:
		enum { _hx_ClassId = 0x49c294c4 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="Ogg2WavSys")
			{ return hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return hx::Object::operator new(inSize+extra,false,"Ogg2WavSys"); }

		hx::ObjectPtr< Ogg2WavSys_obj > __new() {
			hx::ObjectPtr< Ogg2WavSys_obj > __this = new Ogg2WavSys_obj();
			__this->__construct();
			return __this;
		}

		static hx::ObjectPtr< Ogg2WavSys_obj > __alloc(hx::Ctx *_hx_ctx) {
			Ogg2WavSys_obj *__this = (Ogg2WavSys_obj*)(hx::Ctx::alloc(_hx_ctx, sizeof(Ogg2WavSys_obj), false, "Ogg2WavSys"));
			*(void **)__this = Ogg2WavSys_obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(hx::DynamicArray inArgs);
		//~Ogg2WavSys_obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, hx::PropertyAccess inCallProp);
		static bool __SetStatic(const ::String &inString, Dynamic &ioValue, hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_HCSTRING("Ogg2WavSys","\xc4","\x94","\xc2","\x49"); }

		static void __boot();
		static void main();
		static ::Dynamic main_dyn();

		static ::String lapTime(Float time);
		static ::Dynamic lapTime_dyn();

		static ::String platform;
};


#endif /* INCLUDED_Ogg2WavSys */ 
