// Generated by Haxe 3.4.0 (git build development @ 75c0f05)
#ifndef INCLUDED_stb_format_vorbis_data_Floor1
#define INCLUDED_stb_format_vorbis_data_Floor1

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_STACK_FRAME(_hx_pos_b99dd2b338075b52_149_new)
HX_DECLARE_CLASS4(stb,format,vorbis,data,Floor1)

namespace stb{
namespace format{
namespace vorbis{
namespace data{


class HXCPP_CLASS_ATTRIBUTES Floor1_obj : public hx::Object
{
	public:
		typedef hx::Object super;
		typedef Floor1_obj OBJ_;
		Floor1_obj();

	public:
		enum { _hx_ClassId = 0x4e15719a };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="stb.format.vorbis.data.Floor1")
			{ return hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return hx::Object::operator new(inSize+extra,true,"stb.format.vorbis.data.Floor1"); }

		hx::ObjectPtr< Floor1_obj > __new() {
			hx::ObjectPtr< Floor1_obj > __this = new Floor1_obj();
			__this->__construct();
			return __this;
		}

		static hx::ObjectPtr< Floor1_obj > __alloc(hx::Ctx *_hx_ctx) {
			Floor1_obj *__this = (Floor1_obj*)(hx::Ctx::alloc(_hx_ctx, sizeof(Floor1_obj), true, "stb.format.vorbis.data.Floor1"));
			*(void **)__this = Floor1_obj::_hx_vtable;
{
            	HX_STACKFRAME(&_hx_pos_b99dd2b338075b52_149_new)
            	HX_STACK_THIS(__this)
            	}
		
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(hx::DynamicArray inArgs);
		//~Floor1_obj();

		HX_DO_RTTI_ALL;
		hx::Val __Field(const ::String &inString, hx::PropertyAccess inCallProp);
		hx::Val __SetField(const ::String &inString,const hx::Val &inValue, hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_HCSTRING("Floor1","\x05","\x35","\xf5","\x75"); }

		int partitions;
		::Array< int > partitionClassList;
		::Array< int > classDimensions;
		::Array< int > classSubclasses;
		::Array< int > classMasterbooks;
		::Array< ::Dynamic> subclassBooks;
		::Array< int > xlist;
		::Array< int > sortedOrder;
		::Array< ::Dynamic> neighbors;
		int floor1Multiplier;
		int rangebits;
		int values;
};

} // end namespace stb
} // end namespace format
} // end namespace vorbis
} // end namespace data

#endif /* INCLUDED_stb_format_vorbis_data_Floor1 */ 
