// Generated by Haxe 3.4.0 (git build development @ 75c0f05)
#ifndef INCLUDED_stb_format_vorbis_data_Floor
#define INCLUDED_stb_format_vorbis_data_Floor

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_STACK_FRAME(_hx_pos_e2c8ae6b43f2c97b_18_new)
HX_DECLARE_CLASS3(stb,format,vorbis,VorbisDecodeState)
HX_DECLARE_CLASS4(stb,format,vorbis,data,Codebook)
HX_DECLARE_CLASS4(stb,format,vorbis,data,Floor)
HX_DECLARE_CLASS4(stb,format,vorbis,data,Floor0)
HX_DECLARE_CLASS4(stb,format,vorbis,data,Floor1)

namespace stb{
namespace format{
namespace vorbis{
namespace data{


class HXCPP_CLASS_ATTRIBUTES Floor_obj : public hx::Object
{
	public:
		typedef hx::Object super;
		typedef Floor_obj OBJ_;
		Floor_obj();

	public:
		enum { _hx_ClassId = 0x68f77f1b };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="stb.format.vorbis.data.Floor")
			{ return hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return hx::Object::operator new(inSize+extra,true,"stb.format.vorbis.data.Floor"); }

		hx::ObjectPtr< Floor_obj > __new() {
			hx::ObjectPtr< Floor_obj > __this = new Floor_obj();
			__this->__construct();
			return __this;
		}

		static hx::ObjectPtr< Floor_obj > __alloc(hx::Ctx *_hx_ctx) {
			Floor_obj *__this = (Floor_obj*)(hx::Ctx::alloc(_hx_ctx, sizeof(Floor_obj), true, "stb.format.vorbis.data.Floor"));
			*(void **)__this = Floor_obj::_hx_vtable;
{
            	HX_STACKFRAME(&_hx_pos_e2c8ae6b43f2c97b_18_new)
            	HX_STACK_THIS(__this)
            	}
		
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(hx::DynamicArray inArgs);
		//~Floor_obj();

		HX_DO_RTTI_ALL;
		hx::Val __Field(const ::String &inString, hx::PropertyAccess inCallProp);
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, hx::PropertyAccess inCallProp);
		hx::Val __SetField(const ::String &inString,const hx::Val &inValue, hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_HCSTRING("Floor","\xac","\x41","\xc4","\x95"); }

		static  ::stb::format::vorbis::data::Floor read( ::stb::format::vorbis::VorbisDecodeState decodeState,::Array< ::Dynamic> codebooks);
		static ::Dynamic read_dyn();

		 ::stb::format::vorbis::data::Floor0 floor0;
		 ::stb::format::vorbis::data::Floor1 floor1;
		int type;
};

} // end namespace stb
} // end namespace format
} // end namespace vorbis
} // end namespace data

#endif /* INCLUDED_stb_format_vorbis_data_Floor */ 
