// Generated by Haxe 3.4.0 (git build development @ 75c0f05)
#ifndef INCLUDED_stb_format_vorbis_data_Header
#define INCLUDED_stb_format_vorbis_data_Header

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_STACK_FRAME(_hx_pos_d4550658b1516b0f_37_new)
HX_DECLARE_CLASS3(stb,format,vorbis,VorbisDecodeState)
HX_DECLARE_CLASS4(stb,format,vorbis,data,Codebook)
HX_DECLARE_CLASS4(stb,format,vorbis,data,Comment)
HX_DECLARE_CLASS4(stb,format,vorbis,data,Floor)
HX_DECLARE_CLASS4(stb,format,vorbis,data,Header)
HX_DECLARE_CLASS4(stb,format,vorbis,data,Mapping)
HX_DECLARE_CLASS4(stb,format,vorbis,data,Mode)
HX_DECLARE_CLASS4(stb,format,vorbis,data,Residue)

namespace stb{
namespace format{
namespace vorbis{
namespace data{


class HXCPP_CLASS_ATTRIBUTES Header_obj : public hx::Object
{
	public:
		typedef hx::Object super;
		typedef Header_obj OBJ_;
		Header_obj();

	public:
		enum { _hx_ClassId = 0x09b4ba42 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="stb.format.vorbis.data.Header")
			{ return hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return hx::Object::operator new(inSize+extra,true,"stb.format.vorbis.data.Header"); }

		hx::ObjectPtr< Header_obj > __new() {
			hx::ObjectPtr< Header_obj > __this = new Header_obj();
			__this->__construct();
			return __this;
		}

		static hx::ObjectPtr< Header_obj > __alloc(hx::Ctx *_hx_ctx) {
			Header_obj *__this = (Header_obj*)(hx::Ctx::alloc(_hx_ctx, sizeof(Header_obj), true, "stb.format.vorbis.data.Header"));
			*(void **)__this = Header_obj::_hx_vtable;
{
            	HX_STACKFRAME(&_hx_pos_d4550658b1516b0f_37_new)
            	HX_STACK_THIS(__this)
            	}
		
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(hx::DynamicArray inArgs);
		//~Header_obj();

		HX_DO_RTTI_ALL;
		hx::Val __Field(const ::String &inString, hx::PropertyAccess inCallProp);
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, hx::PropertyAccess inCallProp);
		hx::Val __SetField(const ::String &inString,const hx::Val &inValue, hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_HCSTRING("Header","\xad","\x7d","\x94","\x31"); }

		static void __boot();
		static int PACKET_ID;
		static int PACKET_COMMENT;
		static int PACKET_SETUP;
		static  ::stb::format::vorbis::data::Header read( ::stb::format::vorbis::VorbisDecodeState decodeState);
		static ::Dynamic read_dyn();

		int maximumBitRate;
		int nominalBitRate;
		int minimumBitRate;
		int sampleRate;
		int channel;
		int blocksize0;
		int blocksize1;
		::Array< ::Dynamic> codebooks;
		::Array< ::Dynamic> floorConfig;
		::Array< ::Dynamic> residueConfig;
		::Array< ::Dynamic> mapping;
		::Array< ::Dynamic> modes;
		 ::stb::format::vorbis::data::Comment comment;
		::String vendor;
};

} // end namespace stb
} // end namespace format
} // end namespace vorbis
} // end namespace data

#endif /* INCLUDED_stb_format_vorbis_data_Header */ 
