// Generated by Haxe 3.4.0 (git build development @ 75c0f05)
#ifndef INCLUDED_stb_format_vorbis_data_IntPoint
#define INCLUDED_stb_format_vorbis_data_IntPoint

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_STACK_FRAME(_hx_pos_f8792a7fe9c3bf00_12_new)
HX_DECLARE_CLASS4(stb,format,vorbis,data,IntPoint)

namespace stb{
namespace format{
namespace vorbis{
namespace data{


class HXCPP_CLASS_ATTRIBUTES IntPoint_obj : public hx::Object
{
	public:
		typedef hx::Object super;
		typedef IntPoint_obj OBJ_;
		IntPoint_obj();

	public:
		enum { _hx_ClassId = 0x36d6dcd6 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="stb.format.vorbis.data.IntPoint")
			{ return hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return hx::Object::operator new(inSize+extra,false,"stb.format.vorbis.data.IntPoint"); }

		hx::ObjectPtr< IntPoint_obj > __new() {
			hx::ObjectPtr< IntPoint_obj > __this = new IntPoint_obj();
			__this->__construct();
			return __this;
		}

		static hx::ObjectPtr< IntPoint_obj > __alloc(hx::Ctx *_hx_ctx) {
			IntPoint_obj *__this = (IntPoint_obj*)(hx::Ctx::alloc(_hx_ctx, sizeof(IntPoint_obj), false, "stb.format.vorbis.data.IntPoint"));
			*(void **)__this = IntPoint_obj::_hx_vtable;
{
            	HX_STACKFRAME(&_hx_pos_f8792a7fe9c3bf00_12_new)
            	HX_STACK_THIS(__this)
            	}
		
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(hx::DynamicArray inArgs);
		//~IntPoint_obj();

		HX_DO_RTTI_ALL;
		hx::Val __Field(const ::String &inString, hx::PropertyAccess inCallProp);
		hx::Val __SetField(const ::String &inString,const hx::Val &inValue, hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_HCSTRING("IntPoint","\x01","\x91","\xbe","\xe8"); }

		int x;
		int y;
};

} // end namespace stb
} // end namespace format
} // end namespace vorbis
} // end namespace data

#endif /* INCLUDED_stb_format_vorbis_data_IntPoint */ 
