// Generated by Haxe 3.4.0 (git build development @ 75c0f05)
#ifndef INCLUDED_stb_format_vorbis_data_Mapping
#define INCLUDED_stb_format_vorbis_data_Mapping

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS3(stb,format,vorbis,VorbisDecodeState)
HX_DECLARE_CLASS4(stb,format,vorbis,data,Floor)
HX_DECLARE_CLASS4(stb,format,vorbis,data,Mapping)
HX_DECLARE_CLASS4(stb,format,vorbis,data,MappingChannel)

namespace stb{
namespace format{
namespace vorbis{
namespace data{


class HXCPP_CLASS_ATTRIBUTES Mapping_obj : public hx::Object
{
	public:
		typedef hx::Object super;
		typedef Mapping_obj OBJ_;
		Mapping_obj();

	public:
		enum { _hx_ClassId = 0x55e068b9 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="stb.format.vorbis.data.Mapping")
			{ return hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return hx::Object::operator new(inSize+extra,true,"stb.format.vorbis.data.Mapping"); }
		static hx::ObjectPtr< Mapping_obj > __new();
		static hx::ObjectPtr< Mapping_obj > __alloc(hx::Ctx *_hx_ctx);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(hx::DynamicArray inArgs);
		//~Mapping_obj();

		HX_DO_RTTI_ALL;
		hx::Val __Field(const ::String &inString, hx::PropertyAccess inCallProp);
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, hx::PropertyAccess inCallProp);
		hx::Val __SetField(const ::String &inString,const hx::Val &inValue, hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_HCSTRING("Mapping","\xee","\xa2","\xcb","\x11"); }

		static  ::stb::format::vorbis::data::Mapping read( ::stb::format::vorbis::VorbisDecodeState decodeState,int channels);
		static ::Dynamic read_dyn();

		int couplingSteps;
		::Array< ::Dynamic> chan;
		int submaps;
		::Array< int > submapFloor;
		::Array< int > submapResidue;
		void doFloor(::Array< ::Dynamic> floors,int i,int n,::Array< Float > target,::Array< int > finalY,::Array< bool > step2Flag);
		::Dynamic doFloor_dyn();

};

} // end namespace stb
} // end namespace format
} // end namespace vorbis
} // end namespace data

#endif /* INCLUDED_stb_format_vorbis_data_Mapping */ 
