// Generated by Haxe 3.4.0 (git build development @ 75c0f05)
#ifndef INCLUDED_stb_format_vorbis_data_Page
#define INCLUDED_stb_format_vorbis_data_Page

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS3(stb,format,vorbis,VorbisDecodeState)
HX_DECLARE_CLASS4(stb,format,vorbis,data,Page)

namespace stb{
namespace format{
namespace vorbis{
namespace data{


class HXCPP_CLASS_ATTRIBUTES Page_obj : public hx::Object
{
	public:
		typedef hx::Object super;
		typedef Page_obj OBJ_;
		Page_obj();

	public:
		enum { _hx_ClassId = 0x40b183c4 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="stb.format.vorbis.data.Page")
			{ return hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return hx::Object::operator new(inSize+extra,false,"stb.format.vorbis.data.Page"); }
		static hx::ObjectPtr< Page_obj > __new();
		static hx::ObjectPtr< Page_obj > __alloc(hx::Ctx *_hx_ctx);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(hx::DynamicArray inArgs);
		//~Page_obj();

		HX_DO_RTTI_ALL;
		hx::Val __Field(const ::String &inString, hx::PropertyAccess inCallProp);
		hx::Val __SetField(const ::String &inString,const hx::Val &inValue, hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_HCSTRING("Page","\x6f","\x06","\x2b","\x35"); }

		int flag;
		 ::stb::format::vorbis::data::Page clone();
		::Dynamic clone_dyn();

		void start( ::stb::format::vorbis::VorbisDecodeState decodeState);
		::Dynamic start_dyn();

		void startWithoutCapturePattern( ::stb::format::vorbis::VorbisDecodeState decodeState);
		::Dynamic startWithoutCapturePattern_dyn();

};

} // end namespace stb
} // end namespace format
} // end namespace vorbis
} // end namespace data

#endif /* INCLUDED_stb_format_vorbis_data_Page */ 
