// Generated by Haxe 3.4.0 (git build development @ 75c0f05)
#ifndef INCLUDED_stb_format_vorbis_data_Setting
#define INCLUDED_stb_format_vorbis_data_Setting

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS4(stb,format,vorbis,data,Setting)

namespace stb{
namespace format{
namespace vorbis{
namespace data{


class HXCPP_CLASS_ATTRIBUTES Setting_obj : public hx::Object
{
	public:
		typedef hx::Object super;
		typedef Setting_obj OBJ_;
		Setting_obj();

	public:
		enum { _hx_ClassId = 0x390dcf3b };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="stb.format.vorbis.data.Setting")
			{ return hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return hx::Object::operator new(inSize+extra,false,"stb.format.vorbis.data.Setting"); }

		hx::ObjectPtr< Setting_obj > __new() {
			hx::ObjectPtr< Setting_obj > __this = new Setting_obj();
			__this->__construct();
			return __this;
		}

		static hx::ObjectPtr< Setting_obj > __alloc(hx::Ctx *_hx_ctx) {
			Setting_obj *__this = (Setting_obj*)(hx::Ctx::alloc(_hx_ctx, sizeof(Setting_obj), false, "stb.format.vorbis.data.Setting"));
			*(void **)__this = Setting_obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(hx::DynamicArray inArgs);
		//~Setting_obj();

		HX_DO_RTTI_ALL;
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_HCSTRING("Setting","\x70","\x09","\xf9","\xf4"); }

		static void __boot();
		static int MAX_CHANNELS;
		static int PUSHDATA_CRC_COUNT;
		static int FAST_HUFFMAN_LENGTH;
		static int FAST_HUFFMAN_TABLE_SIZE;
		static int FAST_HUFFMAN_TABLE_MASK;
};

} // end namespace stb
} // end namespace format
} // end namespace vorbis
} // end namespace data

#endif /* INCLUDED_stb_format_vorbis_data_Setting */ 
